### ISSUE TITLE
Error for doublet detection

### ISSUE THREAD

**Issue by lh12565** [JonathanShor/DoubletDetection#129]
Hi,
When I execute this command:
```
doublets = clf.fit(raw_counts).predict(p_thresh=1e-16, voter_thresh=0.5)
```
I got a error as below
```
0%|                                                    | 0/50 [00:00<?, ?it/s]/usr/local/python37/lib/python3.7/site-packages/numba/compiler.py:602: NumbaPerformanceWarning:
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "../../../../../../usr/local/python37/lib/python3.7/site-packages/umap/nndescent.py", line 47:
    @numba.njit(parallel=True)
    def nn_descent(
    ^

  self.func_ir.loc))
  0%|                                                    | 0/50 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python37/lib/python3.7/site-packages/doubletdetection/doubletdetection.py", line 248, in fit
    self.all_scores_[i], self.all_log_p_values_[i] = self._one_fit()
  File "/usr/local/python37/lib/python3.7/site-packages/doubletdetection/doubletdetection.py", line 358, in _one_fit
    aug_counts, random_state=self.random_state, resolution=4, directed=False
  File "/usr/local/python37/lib/python3.7/site-packages/scanpy/tools/_louvain.py", line 114, in louvain
    g = utils.get_igraph_from_adjacency(adjacency, directed=directed)
  File "/usr/local/python37/lib/python3.7/site-packages/scanpy/utils.py", line 381, in get_igraph_from_adjacency
    import igraph as ig
  File "/usr/local/python37/lib/python3.7/site-packages/igraph/__init__.py", line 8, in <module>
    raise DeprecationWarning("To avoid name collision with the igraph project, "
DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.
>>> import multiprocessing
>>> doublets = clf.fit(raw_counts).predict(p_thresh=1e-16, voter_thresh=0.5)
  0%|                                                    | 0/50 [00:00<?, ?it/s]/usr/local/python37/lib/python3.7/site-packages/numba/compiler.py:602: NumbaPerformanceWarning:
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "../../../../../../usr/local/python37/lib/python3.7/site-packages/umap/nndescent.py", line 47:
    @numba.njit(parallel=True)
    def nn_descent(
    ^

  self.func_ir.loc))
  0%|                                                    | 0/50 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python37/lib/python3.7/site-packages/doubletdetection/doubletdetection.py", line 248, in fit
    self.all_scores_[i], self.all_log_p_values_[i] = self._one_fit()
  File "/usr/local/python37/lib/python3.7/site-packages/doubletdetection/doubletdetection.py", line 358, in _one_fit
    aug_counts, random_state=self.random_state, resolution=4, directed=False
  File "/usr/local/python37/lib/python3.7/site-packages/scanpy/tools/_louvain.py", line 114, in louvain
    g = utils.get_igraph_from_adjacency(adjacency, directed=directed)
  File "/usr/local/python37/lib/python3.7/site-packages/scanpy/utils.py", line 381, in get_igraph_from_adjacency
    import igraph as ig
  File "/usr/local/python37/lib/python3.7/site-packages/igraph/__init__.py", line 8, in <module>
    raise DeprecationWarning("To avoid name collision with the igraph project, "
DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.
```

**Comment by adamgayoso** [comment]
These warnings come from [umap](https://github.com/lmcinnes/umap/issues/252). We have a line of code in there that uses scanpy, which uses umap to calculate an approximate NN graph. This graph is used for clustering when `use_phenograph==False`. However, we have a small bug that runs this line even when `use_phenograph==True`. We will fix this soon.

**Comment by adamgayoso** [comment]
By the way, are you using `use_phenograph==True`?

**Comment by lh12565** [comment]
I use use_phenograph==False. Although there is a warning that I can ignore, I can't get results.

**Comment by adamgayoso** [comment]
I see...  @lh12565  This might actually have to do with your scanpy version. I see that we don't have scanpy in the setup.py requirements. I will go ahead and fix that soon!

**Comment by duocang** [comment]
hi,

For some reason, I had this error too and it is not even possible to stop the code with ctr +c because the error just pops up consistently. Also, the CPU goes to 100%.

I am sorry to put an image here instead of error message becase I can not stop the code to copy the error meesage.
![image](https://user-images.githubusercontent.com/14146871/103944721-63d53b00-5134-11eb-90b0-c225167baf77.png)


```python
import doubletdetection
import numpy as np
from scipy.sparse import csr_matrix

read_count = np.genfromtxt("../data/read_count_temp.csv", delimiter=",")
read_count = csr_matrix(read_count, dtype=np.float)

clf = doubletdetection.BoostClassifier()
labels = clf.fit(read_count).predict(use_phenograph=False)
```
The example is very tiny, you can try it if you need.
https://1drv.ms/u/s!AtjLM4-mbBLkx85-DWbTACZkWZsT8Q?e=BaAvE0
