### ISSUE TITLE
got "list index out of range" error

### ISSUE THREAD

**Issue by jchenpku** [JonathanShor/DoubletDetection#132]
>>> count = pd.read_csv("exprs.txt", sep="\t", index_col = 0, skiprows =1 )
>>> count.shape
(43243, 10949)
>>> labels = clf.fit(count).predict()
                                                                                                                                                                                             Traceback (most recent call last):
  File "<stdin>", line 1, in <module>                                                                                                                                 | 0/25 [00:00<?, ?it/s]
  File "/software/miniconda3/envs/py3/lib/python3.7/site-packages/doubletdetection/doubletdetection.py", line 248, in fit
    self.all_scores_[i], self.all_log_p_values_[i] = self._one_fit()
  File "/software/miniconda3/envs/py3/lib/python3.7/site-packages/doubletdetection/doubletdetection.py", line 351, in _one_fit
    aug_counts.obsm["X_pca"], **self.phenograph_parameters
  File "/software/miniconda3/envs/py3/lib/python3.7/site-packages/phenograph/cluster.py", line 124, in cluster
    communities, Q = runlouvain(uid, tol=q_tol, time_limit=louvain_time_limit)
  File "/software/miniconda3/envs/py3/lib/python3.7/site-packages/phenograph/core.py", line 266, in runlouvain
    if q[-1] - Q > tol:
IndexError: list index out of range

**Comment by adamgayoso** [comment]
Hi, I'm not sure if you've figured out the solution to your issue, but please do let me know.

**Comment by duocang** [comment]
Hi, @adamgayoso @jchenpku 

I met the same error, do you have any idea?


```python
import doubletdetection
import numpy as np
from scipy.sparse import csr_matrix

read_count = np.genfromtxt("../data/read_count_temp.csv", delimiter=",")
read_count = csr_matrix(read_count, dtype=np.float)

clf = doubletdetection.BoostClassifier()
labels = clf.fit(read_count).predict(use_phenograph=False)
The example is very tiny, you can try it if you need.
https://1drv.ms/u/s!AtjLM4-mbBLkx85-DWbTACZkWZsT8Q?e=BaAvE0
